import task from "./todo.js";
import project from "./project.js";
import store from "./store";
import inbox from "./inbox.js";
import "./style.css";
import addTask from "./DOM_add_task";
import addProject from "./DOM_add_project.js";
import populateContent from "./DOM_project";
window.task = task;
window.project = project;
window.store = store;
window.inbox = inbox;
addTask();
addProject();
populateContent();
