import createTask from "./todo.js";
import createProject from "./project.js";
import store from "./store";
import inbox from "./inbox.js";
import "./style.css";
import populateContent from "./DOM_project.js";
import initNewTaskController from "./newTaskController.js";
import initNewProjectController from "./newProjectController.js";
import initNewTaskSubmissionController from "./newTaskSubmissionController.js";
import initNewProjectSubmissionController from "./newProjectSubmissionController.js";
window.task = createTask;
window.project = createProject;
window.store = store;
window.inbox = inbox;
initNewTaskController();
initNewTaskSubmissionController();
initNewProjectController();
initNewProjectSubmissionController();
populateContent();
